# Generated by Django 4.2.8 on 2024-06-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(verbose_name='Category Description')),
                ('img', models.ImageField(upload_to='post/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('img', models.ImageField(upload_to='sports/', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='meranda.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Sports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Healthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('hygiene', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Hygiene Tips')),
                ('img', models.ImageField(upload_to='health_img/', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthies', to='meranda.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Healthies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('img', models.ImageField(upload_to='foods/', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='meranda.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Foods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('img', models.ImageField(upload_to='designs/', verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='meranda.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Designs',
                'ordering': ['-created_at'],
            },
        ),
    ]
