# Generated by Django 4.2.8 on 2024-06-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meranda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
